name: Build Godot Web & Deploy to Itch.io

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Inject AdSense Credentials
        run: |
          sed -i "s/vsgamer57pid/${{ vars.ADSENSE_PUB_ID }}/g" endlessly-overflowing-palette-v-2-by-papi-res/web_shell.html
          sed -i "s/vsgamer57sid/${{ vars.ADSENSE_SLOT_ID }}/g" endlessly-overflowing-palette-v-2-by-papi-res/web_shell.html

      - name: Godot Web Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.6.2&flavor=stable&slug=linux.x86_64.zip&platform=linux.64
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.6.2&flavor=stable&slug=export_templates.tpz&platform=templates
          relative_project_path: ./endlessly-overflowing-palette-v-2-by-papi-res/
          cache: true
          archive_output: true
          presets_to_export: Web
          relative_export_path: index.html

      - name: Setup Official Butler Tool
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive.zip
          unzip butler.zip -d bin
          chmod +x bin/butler
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Push to Itch.io via Official Butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          butler push /home/runner/.local/share/godot/builds/Web/ vsgamer57/endlessly-overflowing-palette-by-papire:html5
